// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Cariage_API.Data;

namespace TP_Cariage_API.Migrations
{
    [DbContext(typeof(TPCarriageContext))]
    [Migration("20210626063845_Delete_ID_for_Entity")]
    partial class Delete_ID_for_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TP_Cariage_API.Models.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cmnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoTk")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("TenKh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.BenXes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBenXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BenXes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Chats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("NhaXeId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("NhaXeId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.ChiTietVes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GheId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeXeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GheId");

                    b.HasIndex("VeXeId");

                    b.ToTable("ChiTietVes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.ChuyenXes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GioKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LichTrinhId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianDen")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("XeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LichTrinhId");

                    b.HasIndex("XeId");

                    b.ToTable("ChuyenXes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.DiaDiems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDiemDi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiemDens");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Ghes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LoaiGheId")
                        .HasColumnType("int");

                    b.Property<int>("SoCot")
                        .HasColumnType("int");

                    b.Property<int>("SoHang")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("XeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiGheId");

                    b.HasIndex("XeId");

                    b.ToTable("Ghes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.LichTrinhs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiaDiemId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaChuyenDi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KhoangCach")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianUocTinh")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiaDiemId");

                    b.ToTable("LichTrinhs");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.LoaiGhes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GiaGhe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoaiGhes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Messagegroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReceved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("TenGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messagegroups");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descreption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReceved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<int?>("MessagegroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessagegroupId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.NhaXes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BenXeId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongXe")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BenXeId");

                    b.ToTable("NhaXes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.NhanXets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhanXet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhaXeId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungNhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("NhaXeId");

                    b.ToTable("NhanXets");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.VeXes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("ChuyenXeId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChuyenXeId");

                    b.ToTable("VeXes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Xes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GiaGhe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiXe")
                        .HasColumnType("int");

                    b.Property<int?>("NhaXeId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongCot")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHang")
                        .HasColumnType("int");

                    b.Property<string>("TenXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhaXeId");

                    b.ToTable("Xes");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Chats", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.Accounts", "Account")
                        .WithMany("Chats")
                        .HasForeignKey("AccountId");

                    b.HasOne("TP_Cariage_API.Models.NhaXes", "NhaXe")
                        .WithMany("Chats")
                        .HasForeignKey("NhaXeId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.ChiTietVes", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.Ghes", "Ghe")
                        .WithMany("ChiTietVes")
                        .HasForeignKey("GheId");

                    b.HasOne("TP_Cariage_API.Models.VeXes", "VeXe")
                        .WithMany("ChiTietVes")
                        .HasForeignKey("VeXeId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.ChuyenXes", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.LichTrinhs", "LichTrinh")
                        .WithMany("ChuyenXes")
                        .HasForeignKey("LichTrinhId");

                    b.HasOne("TP_Cariage_API.Models.Xes", "Xe")
                        .WithMany("ChuyenXes")
                        .HasForeignKey("XeId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Ghes", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.LoaiGhes", "LoaiGhe")
                        .WithMany("Ghes")
                        .HasForeignKey("LoaiGheId");

                    b.HasOne("TP_Cariage_API.Models.Xes", "Xe")
                        .WithMany("Ghes")
                        .HasForeignKey("XeId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.LichTrinhs", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.DiaDiems", "DiaDiem")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("DiaDiemId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Messagegroups", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.Chats", "Chat")
                        .WithMany("Messagegroups")
                        .HasForeignKey("ChatId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Messages", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.Messagegroups", "Messagegroup")
                        .WithMany("Messages")
                        .HasForeignKey("MessagegroupId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.NhaXes", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.BenXes", "BenXe")
                        .WithMany("NhaXes")
                        .HasForeignKey("BenXeId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.NhanXets", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.Accounts", "Account")
                        .WithMany("NhanXets")
                        .HasForeignKey("AccountId");

                    b.HasOne("TP_Cariage_API.Models.NhaXes", "NhaXe")
                        .WithMany("NhanXets")
                        .HasForeignKey("NhaXeId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.VeXes", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.Accounts", "Account")
                        .WithMany("VeXes")
                        .HasForeignKey("AccountId");

                    b.HasOne("TP_Cariage_API.Models.ChuyenXes", "ChuyenXe")
                        .WithMany("VeXes")
                        .HasForeignKey("ChuyenXeId");
                });

            modelBuilder.Entity("TP_Cariage_API.Models.Xes", b =>
                {
                    b.HasOne("TP_Cariage_API.Models.NhaXes", "NhaXe")
                        .WithMany("Xes")
                        .HasForeignKey("NhaXeId");
                });
#pragma warning restore 612, 618
        }
    }
}
